parameters:
#    arzzzen_cms.example.class: Arzzzen\CmsBundle\Example

services:
#    arzzzen_cms.example:
#        class: %arzzzen_cms.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    sonata.admin.post:
        class: Arzzzen\CmsBundle\Admin\PageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Контент", label: "Страница" }
        arguments:
            - ~
            - Arzzzen\CmsBundle\Entity\Page
            - ~
        calls:
            - [ setTranslationDomain, [ArzzzenCmsBundle]]